export const accountColorPalette = [
  '#155eef',
  '#0891b2',
  '#0f766e',
  '#7c3aed',
  '#b45309',
  '#dc2626',
  '#059669',
  '#1d4ed8',
];

export const defaultAdminSettings = {
  cashWarningThreshold: 150,
  statuses: ['Projected', 'Actual', 'Cleared'],
  statusFilters: ['All', 'Projected', 'Actual', 'Cleared', 'Actual + Cleared'],
  ruleDirections: ['Income', 'Expense', 'Transfer'],
  frequencyUnits: ['Day', 'Week', 'Month'],
  trackingTypes: ['Cash', 'Loan'],
  cashAccountTypes: ['Checking', 'Savings', 'Cash', 'Wallet', 'Brokerage', 'Other'],
  loanAccountTypes: ['Mortgage', 'Car Loan', 'Personal Loan', 'Credit Card', 'Revolving LOC', 'Student Loan', 'Other Debt'],
  loanPaymentFrequencies: ['Monthly', 'Biweekly', 'Weekly', 'Quarterly', 'Annual'],
  budgetDirections: ['Expense', 'Income'],
  budgetModes: ['Limit', 'Goal'],
  categorySuggestions: [
    'Payroll',
    'Rent / Mortgage',
    'Utilities',
    'Insurance',
    'Groceries',
    'Dining',
    'Fuel',
    'Transfer',
    'Debt Payment',
    'Savings',
    'Subscription',
    'Medical',
    'Travel',
    'Shopping',
    'Other',
  ],
};
